version: '3.8'

services:
  e-wallet-bot:
    container_name: e-wallet-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - ewallet-network

networks:
  ewallet-network:
    external: true
    driver: bridge